import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Lang = 'fr' | 'en' | 'it' | 'es';

const LOCALES: Record<Lang, string> = { fr: 'fr-FR', en: 'en-US', it: 'it-IT', es: 'es-ES' };

const translations: Record<Lang, Record<string, string>> = {
    fr: {
        // Navigation
        commander: 'Commander', reserver: "Réserver à l'avance", boutique: 'Boutique',
        mes_bons: 'Mes bons cadeaux', parrainage: 'Parrainage', niveaux: 'Niveaux',
        profil: 'Profil', equipe: 'Mon équipe', commissions: 'Commissions',
        revenus: 'Revenus', deconnexion: 'Déconnexion', connexion: 'Connexion',
        inscription: 'Inscription', envoyer: 'Envoyer', annuler: 'Annuler',
        confirmer: 'Confirmer', chargement: 'Chargement...', erreur: 'Une erreur est survenue',
        points: 'points', courses: 'courses', disponible: 'Disponible',
        hors_ligne: 'Hors ligne', theme: 'Thème', langue: 'Langue',
        nocturne: 'Nocturne', clair: 'Clair', auto: 'Automatique',
        bonne_route: 'Bonne route. - SESAME', ok: 'OK', non: 'Non',
        // Accueil
        bonjour: 'Bonjour', commission_du_mois: 'COMMISSION DU MOIS',
        basee_equipe: 'Basée sur les courses de votre équipe',
        deux_modes_actifs: '2 MODES ACTIFS', reservation_seul: 'RÉSERVATION',
        commander_maintenant: 'Commander maintenant', reserver_avance: "Réserver à l'avance",
        course_immediate_bientot: 'Course immédiate — bientôt disponible',
        mon_compte: 'MON COMPTE', en_cours_label: 'En cours', bons_attente_label: 'Bons attente',
        impossible_donnees: 'Impossible de récupérer les données.',
        // Courses (VTC)
        mes_courses: 'Mes Courses', code_client_pivot: 'CODE CLIENT PIVOT',
        en_attente_chauffeur: "En attente d'acceptation chauffeur",
        chauffeur_assigne: 'CHAUFFEUR ASSIGNÉ', depart_label: 'DÉPART',
        destination_label: 'DESTINATION', montant_label: 'MONTANT',
        annuler_course_titre: 'Annuler la course ?',
        annuler_course_msg: 'Cette action est irréversible. Aucun point ne sera attribué.',
        oui_annuler: 'Oui, annuler',
        telephone_indisponible: 'Téléphone indisponible',
        numero_indisponible: "Le numéro du chauffeur n'est pas encore disponible.",
        impossible_annuler: "Impossible d'annuler la course.",
        aucune_course_active: 'Aucune course active', historique_label: 'HISTORIQUE',
        envoyer_sms_client: 'Envoyer SMS au client', appeler_chauffeur: 'Appeler le chauffeur',
        // Boutique
        echangez_points: 'Échangez vos points contre des expériences exclusives.',
        votre_solde: 'VOTRE SOLDE', impossible_boutique: 'Impossible de charger la boutique.',
        aucune_offre: 'Aucune offre disponible', nouvelles_offres_bientot: 'De nouvelles offres arriveront bientôt.',
        stock_illimite: 'Stock illimité', disponibles: 'disponibles',
        echanger_btn: 'Échanger', insuffisant_btn: 'Insuffisant',
        points_insuffisants: 'Points insuffisants',
        il_vous_faut: 'Il vous faut {requis} pts. Vous avez {solde} pts.',
        echanger_titre: 'Échanger "{nom}" ?',
        echanger_msg: '{requis} points seront déduits de votre solde ({solde} pts).\n\nLe bon sera disponible après validation par l\'équipe SÉSAME.',
        demande_enregistree: 'Demande enregistrée !',
        bon_dispo_notification: "Votre bon sera disponible dès validation par l'équipe SÉSAME. Vous recevrez une notification.",
        erreur_echange: "Erreur lors de l'échange.",
        // Bons cadeaux
        mes_bons_cadeaux: 'Mes Bons Cadeaux', impossible_bons: 'Impossible de récupérer vos bons.',
        aucun_bon: 'Aucun bon cadeau',
        utiliser_points_boutique: 'Utilisez vos points en boutique pour obtenir des bons.',
        aller_boutique_btn: 'Aller à la Boutique',
        points_deduits: 'POINTS DÉDUITS', remis_le: 'REMIS LE', expire_le: 'EXPIRE LE',
        voir_qr_code: '📲 VOIR MON QR CODE',
        bon_attente_validation: "Votre bon sera disponible dès validation par l'équipe SÉSAME.",
        bon_statut_valide: 'Valide — QR disponible', bon_statut_attente: 'En attente de validation',
        bon_statut_utilise: 'Utilisé', bon_statut_expire: 'Expiré',
        bon_statut_refuse: 'Refusé — points recrédités',
        expire_demain: '⚡ "{nom}" expire DEMAIN à {heure} !',
        expire_dans: '⏳ "{nom}" expire dans {jours} jours — {date}',
        // Parrainage
        parrainage_titre: 'PARRAINAGE', votre_code_parrain: 'VOTRE CODE PARRAIN',
        partager_code: 'Partager mon code', filleuls_actifs: 'Filleuls actifs',
        points_gagnes: 'Points gagnés',
        systeme_paliers: 'SYSTÈME DE PALIERS (max 50 pts/filleul)',
        paliers_cumulatifs: 'Les paliers sont cumulatifs par filleul.',
        mes_filleuls: 'MES FILLEULS', aucun_filleul: "Aucun filleul pour l'instant",
        partager_pour_parrainer: 'Partagez votre code pour commencer à parrainer.',
        inscrit_le: 'Inscrit le', courses_effectuees_s: 'course effectuée',
        courses_effectuees_p: 'courses effectuées',
        impossible_parrainage: 'Impossible de charger les données de parrainage.',
        rejoins_sesame: 'Rejoins SESAME avec mon code parrain : {code}\n\nBénéficiez de véhicules premium et de récompenses exclusives.',
        // Niveaux
        niveaux_titre: 'Niveaux SÉSAME', vos_points: 'VOS POINTS', niveau_label: 'Niveau',
        pts_pour_atteindre: 'pts pour atteindre', des_inscription: "Dès l'inscription",
        a_partir_de: 'À partir de', en_cours_badge: 'EN COURS',
        comment_progresser: 'COMMENT PROGRESSER',
        gagner_1pt_10eur: 'Gagnez 1 point pour chaque tranche de 10 € de course prescrite.',
        code_pivot_info: 'Le code pivot doit être validé pour que les points soient crédités.',
        niveau_max_atteint: '🏆 NIVEAU MAXIMUM ATTEINT',
        // Commissions
        taux_par_course: 'Taux : {taux}% TTC par course', ce_mois: 'Ce mois',
        versement_1er_mois: 'Versement le 1er du mois suivant par virement SEPA',
        historique_12_mois: 'Historique (12 derniers mois)', total_cumule: 'Total cumulé',
        aucune_commission: "Aucune commission enregistrée pour l'instant.",
        courses_ca: '{nb} courses · {ca} € CA',
        // Profil
        mon_profil: 'Mon Profil',
        gerer_infos: 'Gérez vos informations personnelles et professionnelles.',
        prenom_label: 'PRÉNOM', nom_label: 'NOM', telephone_label: 'TÉLÉPHONE',
        metier_label: 'MÉTIER', etablissement_label: 'ÉTABLISSEMENT',
        profil_maj: 'Profil mis à jour.',
        impossible_charger_profil: 'Impossible de charger les informations de profil.',
        impossible_maj_profil: 'Impossible de mettre à jour le profil.',
        enregistrer: 'ENREGISTRER LES MODIFICATIONS',
        // Équipe
        ajouter_btn: '+ Ajouter',
        sous_comptes_info: 'Sous-comptes employés de votre établissement',
        aucun_employe: "Aucun employé pour l'instant.",
        champs_obligatoires: 'Tous les champs obligatoires doivent être remplis.',
        impossible_ajouter_employe: "Impossible d'ajouter l'employé.",
        nouveau_employe: 'Nouvel employé', prenom_placeholder: 'Prénom',
        nom_placeholder: 'Nom', email_placeholder: 'Email',
        telephone_placeholder: 'Téléphone', metier_placeholder: 'Métier (optionnel)',
        mdp_placeholder: 'Mot de passe',
    },
    en: {
        // Navigation
        commander: 'Order now', reserver: 'Book in advance', boutique: 'Shop',
        mes_bons: 'My gift vouchers', parrainage: 'Referral', niveaux: 'Levels',
        profil: 'Profile', equipe: 'My team', commissions: 'Commissions',
        revenus: 'Earnings', deconnexion: 'Logout', connexion: 'Login',
        inscription: 'Sign up', envoyer: 'Send', annuler: 'Cancel',
        confirmer: 'Confirm', chargement: 'Loading...', erreur: 'An error occurred',
        points: 'points', courses: 'rides', disponible: 'Available',
        hors_ligne: 'Offline', theme: 'Theme', langue: 'Language',
        nocturne: 'Dark', clair: 'Light', auto: 'Automatic',
        bonne_route: 'Safe travels. - SESAME', ok: 'OK', non: 'No',
        // Accueil
        bonjour: 'Hello', commission_du_mois: "THIS MONTH'S COMMISSION",
        basee_equipe: "Based on your team's rides",
        deux_modes_actifs: '2 ACTIVE MODES', reservation_seul: 'BOOKING ONLY',
        commander_maintenant: 'Order now', reserver_avance: 'Book in advance',
        course_immediate_bientot: 'Immediate ride — coming soon',
        mon_compte: 'MY ACCOUNT', en_cours_label: 'In progress', bons_attente_label: 'Pending vouchers',
        impossible_donnees: 'Unable to retrieve data.',
        // Courses
        mes_courses: 'My Rides', code_client_pivot: 'CLIENT PIVOT CODE',
        en_attente_chauffeur: 'Waiting for driver acceptance',
        chauffeur_assigne: 'ASSIGNED DRIVER', depart_label: 'DEPARTURE',
        destination_label: 'DESTINATION', montant_label: 'AMOUNT',
        annuler_course_titre: 'Cancel the ride?',
        annuler_course_msg: 'This action is irreversible. No points will be awarded.',
        oui_annuler: 'Yes, cancel',
        telephone_indisponible: 'Phone unavailable',
        numero_indisponible: "The driver's number is not yet available.",
        impossible_annuler: 'Unable to cancel the ride.',
        aucune_course_active: 'No active ride', historique_label: 'HISTORY',
        envoyer_sms_client: 'Send SMS to client', appeler_chauffeur: 'Call driver',
        // Boutique
        echangez_points: 'Exchange your points for exclusive experiences.',
        votre_solde: 'YOUR BALANCE', impossible_boutique: 'Unable to load the shop.',
        aucune_offre: 'No offers available', nouvelles_offres_bientot: 'New offers coming soon.',
        stock_illimite: 'Unlimited stock', disponibles: 'available',
        echanger_btn: 'Exchange', insuffisant_btn: 'Insufficient',
        points_insuffisants: 'Insufficient points',
        il_vous_faut: 'You need {requis} pts. You have {solde} pts.',
        echanger_titre: 'Exchange "{nom}"?',
        echanger_msg: '{requis} points will be deducted from your balance ({solde} pts).\n\nThe voucher will be available after validation by the SÉSAME team.',
        demande_enregistree: 'Request registered!',
        bon_dispo_notification: 'Your voucher will be available once validated by the SÉSAME team. You will receive a notification.',
        erreur_echange: 'Error during exchange.',
        // Bons cadeaux
        mes_bons_cadeaux: 'My Gift Vouchers', impossible_bons: 'Unable to retrieve your vouchers.',
        aucun_bon: 'No gift voucher',
        utiliser_points_boutique: 'Use your points in the shop to get vouchers.',
        aller_boutique_btn: 'Go to the Shop',
        points_deduits: 'POINTS DEDUCTED', remis_le: 'ISSUED ON', expire_le: 'EXPIRES ON',
        voir_qr_code: '📲 VIEW MY QR CODE',
        bon_attente_validation: 'Your voucher will be available once validated by the SÉSAME team.',
        bon_statut_valide: 'Valid — QR available', bon_statut_attente: 'Pending validation',
        bon_statut_utilise: 'Used', bon_statut_expire: 'Expired',
        bon_statut_refuse: 'Refused — points refunded',
        expire_demain: '⚡ "{nom}" expires TOMORROW at {heure}!',
        expire_dans: '⏳ "{nom}" expires in {jours} days — {date}',
        // Parrainage
        parrainage_titre: 'REFERRAL', votre_code_parrain: 'YOUR REFERRAL CODE',
        partager_code: 'Share my code', filleuls_actifs: 'Active referrals',
        points_gagnes: 'Points earned',
        systeme_paliers: 'TIER SYSTEM (max 50 pts/referral)',
        paliers_cumulatifs: 'Tiers are cumulative per referral.',
        mes_filleuls: 'MY REFERRALS', aucun_filleul: 'No referrals yet',
        partager_pour_parrainer: 'Share your code to start referring.',
        inscrit_le: 'Registered on', courses_effectuees_s: 'ride completed',
        courses_effectuees_p: 'rides completed',
        impossible_parrainage: 'Unable to load referral data.',
        rejoins_sesame: 'Join SESAME with my referral code: {code}\n\nEnjoy premium vehicles and exclusive rewards.',
        // Niveaux
        niveaux_titre: 'SÉSAME Levels', vos_points: 'YOUR POINTS', niveau_label: 'Level',
        pts_pour_atteindre: 'pts to reach', des_inscription: 'From registration',
        a_partir_de: 'From', en_cours_badge: 'CURRENT',
        comment_progresser: 'HOW TO PROGRESS',
        gagner_1pt_10eur: 'Earn 1 point for every 10 € of ride prescribed.',
        code_pivot_info: 'The pivot code must be validated for points to be credited.',
        niveau_max_atteint: '🏆 MAXIMUM LEVEL REACHED',
        // Commissions
        taux_par_course: 'Rate: {taux}% incl. tax per ride', ce_mois: 'This month',
        versement_1er_mois: 'Payment on the 1st of next month by SEPA transfer',
        historique_12_mois: 'History (last 12 months)', total_cumule: 'Total accumulated',
        aucune_commission: 'No commissions recorded yet.',
        courses_ca: '{nb} rides · {ca} € revenue',
        // Profil
        mon_profil: 'My Profile',
        gerer_infos: 'Manage your personal and professional information.',
        prenom_label: 'FIRST NAME', nom_label: 'LAST NAME', telephone_label: 'PHONE',
        metier_label: 'OCCUPATION', etablissement_label: 'ESTABLISHMENT',
        profil_maj: 'Profile updated.',
        impossible_charger_profil: 'Unable to load profile information.',
        impossible_maj_profil: 'Unable to update profile.',
        enregistrer: 'SAVE CHANGES',
        // Équipe
        ajouter_btn: '+ Add',
        sous_comptes_info: 'Employee sub-accounts of your establishment',
        aucun_employe: 'No employees yet.',
        champs_obligatoires: 'All required fields must be filled in.',
        impossible_ajouter_employe: 'Unable to add the employee.',
        nouveau_employe: 'New employee', prenom_placeholder: 'First name',
        nom_placeholder: 'Last name', email_placeholder: 'Email',
        telephone_placeholder: 'Phone', metier_placeholder: 'Occupation (optional)',
        mdp_placeholder: 'Password',
    },
    it: {
        // Navigation
        commander: 'Ordina ora', reserver: 'Prenota in anticipo', boutique: 'Negozio',
        mes_bons: 'I miei buoni regalo', parrainage: 'Referral', niveaux: 'Livelli',
        profil: 'Profilo', equipe: 'Il mio team', commissions: 'Commissioni',
        revenus: 'Guadagni', deconnexion: 'Disconnetti', connexion: 'Accesso',
        inscription: 'Registrati', envoyer: 'Invia', annuler: 'Annulla',
        confirmer: 'Conferma', chargement: 'Caricamento...', erreur: 'Si è verificato un errore',
        points: 'punti', courses: 'corse', disponible: 'Disponibile',
        hors_ligne: 'Non disponibile', theme: 'Tema', langue: 'Lingua',
        nocturne: 'Scuro', clair: 'Chiaro', auto: 'Automatico',
        bonne_route: 'Buon viaggio. - SESAME', ok: 'OK', non: 'No',
        // Accueil
        bonjour: 'Ciao', commission_du_mois: 'COMMISSIONE DEL MESE',
        basee_equipe: 'Basata sulle corse del tuo team',
        deux_modes_actifs: '2 MODALITÀ ATTIVE', reservation_seul: 'PRENOTAZIONE',
        commander_maintenant: 'Ordina ora', reserver_avance: 'Prenota in anticipo',
        course_immediate_bientot: 'Corsa immediata — prossimamente',
        mon_compte: 'IL MIO ACCOUNT', en_cours_label: 'In corso', bons_attente_label: 'Buoni in attesa',
        impossible_donnees: 'Impossibile recuperare i dati.',
        // Courses
        mes_courses: 'Le Mie Corse', code_client_pivot: 'CODICE CLIENTE PIVOT',
        en_attente_chauffeur: "In attesa di accettazione dell'autista",
        chauffeur_assigne: 'AUTISTA ASSEGNATO', depart_label: 'PARTENZA',
        destination_label: 'DESTINAZIONE', montant_label: 'IMPORTO',
        annuler_course_titre: 'Annullare la corsa?',
        annuler_course_msg: 'Questa azione è irreversibile. Nessun punto verrà assegnato.',
        oui_annuler: 'Sì, annulla',
        telephone_indisponible: 'Telefono non disponibile',
        numero_indisponible: "Il numero dell'autista non è ancora disponibile.",
        impossible_annuler: 'Impossibile annullare la corsa.',
        aucune_course_active: 'Nessuna corsa attiva', historique_label: 'STORICO',
        envoyer_sms_client: 'Invia SMS al cliente', appeler_chauffeur: "Chiama l'autista",
        // Boutique
        echangez_points: 'Scambia i tuoi punti per esperienze esclusive.',
        votre_solde: 'IL TUO SALDO', impossible_boutique: 'Impossibile caricare il negozio.',
        aucune_offre: 'Nessuna offerta disponibile', nouvelles_offres_bientot: 'Nuove offerte in arrivo.',
        stock_illimite: 'Stock illimitato', disponibles: 'disponibili',
        echanger_btn: 'Scambia', insuffisant_btn: 'Insufficiente',
        points_insuffisants: 'Punti insufficienti',
        il_vous_faut: 'Servono {requis} pts. Ne hai {solde}.',
        echanger_titre: 'Scambiare "{nom}"?',
        echanger_msg: '{requis} punti verranno detratti dal tuo saldo ({solde} pts).\n\nIl buono sarà disponibile dopo la validazione del team SÉSAME.',
        demande_enregistree: 'Richiesta registrata!',
        bon_dispo_notification: 'Il tuo buono sarà disponibile dopo la validazione del team SÉSAME. Riceverai una notifica.',
        erreur_echange: 'Errore durante lo scambio.',
        // Bons cadeaux
        mes_bons_cadeaux: 'I Miei Buoni Regalo', impossible_bons: 'Impossibile recuperare i tuoi buoni.',
        aucun_bon: 'Nessun buono regalo',
        utiliser_points_boutique: 'Usa i tuoi punti nel negozio per ottenere buoni.',
        aller_boutique_btn: 'Vai al Negozio',
        points_deduits: 'PUNTI DEDOTTI', remis_le: 'EMESSO IL', expire_le: 'SCADE IL',
        voir_qr_code: '📲 VEDI IL MIO QR CODE',
        bon_attente_validation: 'Il tuo buono sarà disponibile dopo la validazione del team SÉSAME.',
        bon_statut_valide: 'Valido — QR disponibile', bon_statut_attente: 'In attesa di validazione',
        bon_statut_utilise: 'Utilizzato', bon_statut_expire: 'Scaduto',
        bon_statut_refuse: 'Rifiutato — punti riaccreditati',
        expire_demain: '⚡ "{nom}" scade DOMANI alle {heure}!',
        expire_dans: '⏳ "{nom}" scade tra {jours} giorni — {date}',
        // Parrainage
        parrainage_titre: 'REFERRAL', votre_code_parrain: 'IL TUO CODICE REFERRAL',
        partager_code: 'Condividi il mio codice', filleuls_actifs: 'Referral attivi',
        points_gagnes: 'Punti guadagnati',
        systeme_paliers: 'SISTEMA A LIVELLI (max 50 pts/referral)',
        paliers_cumulatifs: 'I livelli sono cumulativi per referral.',
        mes_filleuls: 'I MIEI REFERRAL', aucun_filleul: 'Nessun referral ancora',
        partager_pour_parrainer: 'Condividi il tuo codice per iniziare a fare referral.',
        inscrit_le: 'Iscritto il', courses_effectuees_s: 'corsa effettuata',
        courses_effectuees_p: 'corse effettuate',
        impossible_parrainage: 'Impossibile caricare i dati di referral.',
        rejoins_sesame: 'Unisciti a SESAME con il mio codice: {code}\n\nGoditi veicoli premium e premi esclusivi.',
        // Niveaux
        niveaux_titre: 'Livelli SÉSAME', vos_points: 'I TUOI PUNTI', niveau_label: 'Livello',
        pts_pour_atteindre: 'pts per raggiungere', des_inscription: "Dall'iscrizione",
        a_partir_de: 'Da', en_cours_badge: 'ATTUALE',
        comment_progresser: 'COME PROGREDIRE',
        gagner_1pt_10eur: 'Guadagna 1 punto per ogni 10 € di corsa prescritta.',
        code_pivot_info: 'Il codice pivot deve essere validato affinché i punti vengano accreditati.',
        niveau_max_atteint: '🏆 LIVELLO MASSIMO RAGGIUNTO',
        // Commissions
        taux_par_course: 'Tasso: {taux}% IVA inclusa per corsa', ce_mois: 'Questo mese',
        versement_1er_mois: 'Pagamento il 1° del mese successivo tramite bonifico SEPA',
        historique_12_mois: 'Storico (ultimi 12 mesi)', total_cumule: 'Totale accumulato',
        aucune_commission: 'Nessuna commissione registrata per ora.',
        courses_ca: '{nb} corse · {ca} € CA',
        // Profil
        mon_profil: 'Il Mio Profilo',
        gerer_infos: 'Gestisci le tue informazioni personali e professionali.',
        prenom_label: 'NOME', nom_label: 'COGNOME', telephone_label: 'TELEFONO',
        metier_label: 'PROFESSIONE', etablissement_label: 'STABILIMENTO',
        profil_maj: 'Profilo aggiornato.',
        impossible_charger_profil: 'Impossibile caricare le informazioni del profilo.',
        impossible_maj_profil: 'Impossibile aggiornare il profilo.',
        enregistrer: 'SALVA MODIFICHE',
        // Équipe
        ajouter_btn: '+ Aggiungi',
        sous_comptes_info: 'Sotto-account dipendenti del tuo stabilimento',
        aucun_employe: 'Nessun dipendente per ora.',
        champs_obligatoires: 'Tutti i campi obbligatori devono essere compilati.',
        impossible_ajouter_employe: 'Impossibile aggiungere il dipendente.',
        nouveau_employe: 'Nuovo dipendente', prenom_placeholder: 'Nome',
        nom_placeholder: 'Cognome', email_placeholder: 'Email',
        telephone_placeholder: 'Telefono', metier_placeholder: 'Professione (opzionale)',
        mdp_placeholder: 'Password',
    },
    es: {
        // Navigation
        commander: 'Pedir ahora', reserver: 'Reservar con antelación', boutique: 'Tienda',
        mes_bons: 'Mis bonos regalo', parrainage: 'Referidos', niveaux: 'Niveles',
        profil: 'Perfil', equipe: 'Mi equipo', commissions: 'Comisiones',
        revenus: 'Ingresos', deconnexion: 'Cerrar sesión', connexion: 'Iniciar sesión',
        inscription: 'Registrarse', envoyer: 'Enviar', annuler: 'Cancelar',
        confirmer: 'Confirmar', chargement: 'Cargando...', erreur: 'Se ha producido un error',
        points: 'puntos', courses: 'viajes', disponible: 'Disponible',
        hors_ligne: 'Desconectado', theme: 'Tema', langue: 'Idioma',
        nocturne: 'Oscuro', clair: 'Claro', auto: 'Automático',
        bonne_route: 'Buen viaje. - SESAME', ok: 'OK', non: 'No',
        // Accueil
        bonjour: 'Hola', commission_du_mois: 'COMISIÓN DEL MES',
        basee_equipe: 'Basada en los viajes de tu equipo',
        deux_modes_actifs: '2 MODOS ACTIVOS', reservation_seul: 'RESERVA',
        commander_maintenant: 'Pedir ahora', reserver_avance: 'Reservar con antelación',
        course_immediate_bientot: 'Viaje inmediato — próximamente',
        mon_compte: 'MI CUENTA', en_cours_label: 'En curso', bons_attente_label: 'Bonos pendientes',
        impossible_donnees: 'Imposible recuperar datos.',
        // Courses
        mes_courses: 'Mis Viajes', code_client_pivot: 'CÓDIGO CLIENTE PIVOTE',
        en_attente_chauffeur: 'Esperando aceptación del conductor',
        chauffeur_assigne: 'CONDUCTOR ASIGNADO', depart_label: 'SALIDA',
        destination_label: 'DESTINO', montant_label: 'IMPORTE',
        annuler_course_titre: '¿Cancelar el viaje?',
        annuler_course_msg: 'Esta acción es irreversible. No se asignarán puntos.',
        oui_annuler: 'Sí, cancelar',
        telephone_indisponible: 'Teléfono no disponible',
        numero_indisponible: 'El número del conductor aún no está disponible.',
        impossible_annuler: 'Imposible cancelar el viaje.',
        aucune_course_active: 'Ningún viaje activo', historique_label: 'HISTORIAL',
        envoyer_sms_client: 'Enviar SMS al cliente', appeler_chauffeur: 'Llamar al conductor',
        // Boutique
        echangez_points: 'Canjea tus puntos por experiencias exclusivas.',
        votre_solde: 'TU SALDO', impossible_boutique: 'Imposible cargar la tienda.',
        aucune_offre: 'Sin ofertas disponibles', nouvelles_offres_bientot: 'Nuevas ofertas próximamente.',
        stock_illimite: 'Stock ilimitado', disponibles: 'disponibles',
        echanger_btn: 'Canjear', insuffisant_btn: 'Insuficiente',
        points_insuffisants: 'Puntos insuficientes',
        il_vous_faut: 'Necesitas {requis} pts. Tienes {solde} pts.',
        echanger_titre: '¿Canjear "{nom}"?',
        echanger_msg: '{requis} puntos serán deducidos de tu saldo ({solde} pts).\n\nEl bono estará disponible después de la validación del equipo SÉSAME.',
        demande_enregistree: '¡Solicitud registrada!',
        bon_dispo_notification: 'Tu bono estará disponible una vez validado por el equipo SÉSAME. Recibirás una notificación.',
        erreur_echange: 'Error durante el canje.',
        // Bons cadeaux
        mes_bons_cadeaux: 'Mis Bonos Regalo', impossible_bons: 'Imposible recuperar tus bonos.',
        aucun_bon: 'Sin bonos regalo',
        utiliser_points_boutique: 'Usa tus puntos en la tienda para obtener bonos.',
        aller_boutique_btn: 'Ir a la Tienda',
        points_deduits: 'PUNTOS DEDUCIDOS', remis_le: 'EMITIDO EL', expire_le: 'VENCE EL',
        voir_qr_code: '📲 VER MI QR CODE',
        bon_attente_validation: 'Tu bono estará disponible una vez validado por el equipo SÉSAME.',
        bon_statut_valide: 'Válido — QR disponible', bon_statut_attente: 'Pendiente de validación',
        bon_statut_utilise: 'Utilizado', bon_statut_expire: 'Caducado',
        bon_statut_refuse: 'Rechazado — puntos reacreditados',
        expire_demain: '⚡ "{nom}" vence MAÑANA a las {heure}!',
        expire_dans: '⏳ "{nom}" vence en {jours} días — {date}',
        // Parrainage
        parrainage_titre: 'REFERIDOS', votre_code_parrain: 'TU CÓDIGO DE REFERIDO',
        partager_code: 'Compartir mi código', filleuls_actifs: 'Referidos activos',
        points_gagnes: 'Puntos ganados',
        systeme_paliers: 'SISTEMA DE NIVELES (máx. 50 pts/referido)',
        paliers_cumulatifs: 'Los niveles son acumulativos por referido.',
        mes_filleuls: 'MIS REFERIDOS', aucun_filleul: 'Sin referidos aún',
        partager_pour_parrainer: 'Comparte tu código para empezar a referir.',
        inscrit_le: 'Registrado el', courses_effectuees_s: 'viaje completado',
        courses_effectuees_p: 'viajes completados',
        impossible_parrainage: 'Imposible cargar los datos de referidos.',
        rejoins_sesame: 'Únete a SESAME con mi código: {code}\n\nDisfruta de vehículos premium y recompensas exclusivas.',
        // Niveaux
        niveaux_titre: 'Niveles SÉSAME', vos_points: 'TUS PUNTOS', niveau_label: 'Nivel',
        pts_pour_atteindre: 'pts para alcanzar', des_inscription: 'Desde el registro',
        a_partir_de: 'Desde', en_cours_badge: 'ACTUAL',
        comment_progresser: 'CÓMO PROGRESAR',
        gagner_1pt_10eur: 'Gana 1 punto por cada 10 € de viaje prescrito.',
        code_pivot_info: 'El código pivote debe ser validado para que se acrediten los puntos.',
        niveau_max_atteint: '🏆 NIVEL MÁXIMO ALCANZADO',
        // Commissions
        taux_par_course: 'Tasa: {taux}% IVA incluido por viaje', ce_mois: 'Este mes',
        versement_1er_mois: 'Pago el 1 del mes siguiente por transferencia SEPA',
        historique_12_mois: 'Historial (últimos 12 meses)', total_cumule: 'Total acumulado',
        aucune_commission: 'Sin comisiones registradas por ahora.',
        courses_ca: '{nb} viajes · {ca} € CA',
        // Profil
        mon_profil: 'Mi Perfil',
        gerer_infos: 'Gestiona tu información personal y profesional.',
        prenom_label: 'NOMBRE', nom_label: 'APELLIDO', telephone_label: 'TELÉFONO',
        metier_label: 'PROFESIÓN', etablissement_label: 'ESTABLECIMIENTO',
        profil_maj: 'Perfil actualizado.',
        impossible_charger_profil: 'Imposible cargar la información del perfil.',
        impossible_maj_profil: 'Imposible actualizar el perfil.',
        enregistrer: 'GUARDAR CAMBIOS',
        // Équipe
        ajouter_btn: '+ Añadir',
        sous_comptes_info: 'Subcuentas de empleados de tu establecimiento',
        aucun_employe: 'Sin empleados por ahora.',
        champs_obligatoires: 'Todos los campos obligatorios deben ser completados.',
        impossible_ajouter_employe: 'Imposible agregar al empleado.',
        nouveau_employe: 'Nuevo empleado', prenom_placeholder: 'Nombre',
        nom_placeholder: 'Apellido', email_placeholder: 'Email',
        telephone_placeholder: 'Teléfono', metier_placeholder: 'Profesión (opcional)',
        mdp_placeholder: 'Contraseña',
    },
};

interface LanguageContextValue {
    lang: Lang;
    setLang: (l: Lang) => void;
    t: (key: string) => string;
    locale: string;
}

const LanguageContext = createContext<LanguageContextValue>({
    lang: 'fr', setLang: () => {}, t: (k) => k, locale: 'fr-FR',
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLangState] = useState<Lang>('fr');

    useEffect(() => {
        AsyncStorage.getItem('sesame_lang').then(v => {
            if (v === 'fr' || v === 'en' || v === 'it' || v === 'es') setLangState(v);
        });
    }, []);

    const setLang = (l: Lang) => {
        setLangState(l);
        AsyncStorage.setItem('sesame_lang', l);
    };

    const t = (key: string) => translations[lang][key] ?? translations['fr'][key] ?? key;
    const locale = LOCALES[lang];

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, locale }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    return useContext(LanguageContext);
}
